spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/valid_db
    username: valid_user
    password: valid_pwd
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8080